# Generated by Django 5.1 on 2024-08-29 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('cod_produto', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código do Produto')),
                ('nome_produto', models.CharField(max_length=45, verbose_name='Nome do Produto')),
                ('descricao_produto', models.TextField(max_length=600, verbose_name='Descrição do Produto')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('porc_desconto', models.IntegerField(verbose_name='Porcentagem de Desconto do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código do Cliente')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('cpf_cliente', models.CharField(max_length=15, verbose_name='CPF do Cliente')),
                ('telefone01_cliente', models.CharField(max_length=15, verbose_name='Telefone (01) do Cliente')),
                ('telefone02_cliente', models.CharField(max_length=15, verbose_name='Telefone (02) do Cliente')),
                ('email_cliente', models.EmailField(max_length=260, verbose_name='E-mail do Cliente')),
                ('senha_cliente', models.CharField(max_length=20, verbose_name='Senha do Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('num_mesa', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número da Mesa')),
                ('capacidade_mesa', models.IntegerField(verbose_name='Capacidade de pessoas da Mesa')),
                ('descricao_mesa', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código da Reserva')),
                ('qtd_pessoas', models.IntegerField(verbose_name='Quantidade de Pessoas')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('horario_reserva', models.TimeField(verbose_name='Horário da Reserva')),
                ('tempo_tolerancia', models.IntegerField(verbose_name='Tempo de Tolerância de Atraso')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_mesas_reservadas', models.IntegerField(verbose_name='Quantidade de Mesas Reservadas')),
                ('num_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mesa')),
                ('cod_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.reserva')),
            ],
        ),
    ]
